"""LeCroy waveform descriptor constants."""

from .header import (
    EXPANDED_TRACE_NAMES,
    KNOWN_TRACE_NAMES,
    PROCESSING_TYPES,
    RECORD_TYPES,
    TIMEBASE_IDS,
    VERT_COUPLINGS,
    VERT_GAIN_IDS,
    WAVEDESC,
    WAVEDESC_FMT,
    WAVEDESC_SIZE,
)

__all__ = [
    "EXPANDED_TRACE_NAMES",
    "KNOWN_TRACE_NAMES",
    "PROCESSING_TYPES",
    "RECORD_TYPES",
    "TIMEBASE_IDS",
    "VERT_COUPLINGS",
    "VERT_GAIN_IDS",
    "WAVEDESC",
    "WAVEDESC_FMT",
    "WAVEDESC_SIZE",
]
